<p style="font-family: Arial; font-size:3.75vw;color:purple; font-style:bold"><br>
Classification Exercise Notebook
</p><br>

# Exercise Notebook Instructions

### 1. Important: Only modify the cells which instruct you to modify them - leave "do not modify" cells alone.  

The code which tests your responses assumes you have run the startup/read-only code exactly.

### 2. Work through the notebook in order.

Some of the steps depend on previous, so you'll want to move through the notebook in order.

### 3. It is okay to use numpy libraries.

You may find some of these questions are fairly straightforward to answer using built-in numpy functions.  That's totally okay - part of the point of these exercises is to familiarize you with the commonly used numpy functions.

### 4. Seek help if stuck

If you get stuck, don't worry!  You can either review the videos/notebooks from this week, ask in the course forums, or look to the solutions for the correct answer.  BUT, be careful about looking to the solutions too quickly.  Struggling to get the right answer is an important part of the learning process.

In [75]:
# DO NOT MODIFY

# import appropriate libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier

In [57]:
# DO NOT MODIFY

# we will use the daily weather dataset of this exercise.

def get_data():
    return pd.read_csv('../weather/daily_weather.csv')

df = get_data()

<p style="font-family: Arial; font-size:2.75vw;color:purple; font-style:bold"><br>

Exercise 1: Detect if NULLs Exist in the Data<br><br></p>


In the cell below, modify the function to RETURN True if there exists a NULL value in data given as input, otherwise False

In [58]:
any(df.isna())

True

In [59]:
# modify this cell

def detect_nulls(matx):
    ### BEGIN SOLUTION
    response = any(matx.isna())
    return response
    ### END SOLUTION

In [60]:
# DO NOT MODIFY
ans = True

try: assert np.alltrue(detect_nulls(df) == ans)
except AssertionError as e: print("Try again, your output did not match the expected answer above")

<p style="font-family: Arial; font-size:2.75vw;color:purple; font-style:bold"><br>

Exercise 2: Data Cleaning<br><br></p>


In the cell below, modify the function to remove every row that has atleast one NULL,
and RETURN a new data frame.

In [61]:
# modify this cell

def clean_data(matx):
    ### BEGIN SOLUTION
    return matx.dropna(axis=0)
    ### END SOLUTION

In [62]:
# DO NOT MODIFY

try: 
    df2=clean_data(df)
    assert np.alltrue(df2.shape[0] == 1064)
except AssertionError as e: print("Try again")

In [63]:
df2.describe()

,number,air_pressure_9am,air_temp_9am,avg_wind_direction_9am,avg_wind_speed_9am,max_wind_direction_9am,max_wind_speed_9am,rain_accumulation_9am,rain_duration_9am,relative_humidity_9am,relative_humidity_3pm
count,1064.000000,1064.000000,1064.000000,1064.000000,1064.000000,1064.000000,1064.000000,1064.000000,1064.000000,1064.000000,1064.000000
mean,545.001880,918.903180,65.022609,142.306756,5.485793,148.480424,6.999714,0.182023,266.393697,34.077440,35.148381
std,316.796111,3.179040,11.168033,69.149472,4.534427,67.154911,5.590790,1.534493,1503.092216,25.356668,22.365475
min,0.000000,907.990000,36.752000,15.500000,0.693451,28.900000,1.185578,0.000000,0.000000,6.090000,5.300000
25%,269.750000,916.595376,57.398000,65.979244,2.245529,76.335351,3.064608,0.000000,0.000000,15.093365,17.360468
50%,543.500000,918.942281,65.778479,165.937461,3.869906,176.350000,4.943637,0.000000,0.000000,23.135000,24.371286
75%,819.250000,921.169054,73.530872,191.100000,7.264463,201.125000,8.747888,0.000000,0.000000,44.660000,51.922500
max,1094.000000,929.320000,98.906000,343.400000,23.554978,312.200000,29.840780,24.020000,17704.000000,92.620000,92.250000

<p style="font-family: Arial; font-size:2.75vw;color:purple; font-style:bold"><br>

Exercise 3: Convert to a Classification Task<br><br></p>

In the cell below, modify the function that takes three inputs: a dataframe, a column name C, and a threshold value X.
The function has to create a new column called 'target' which is 1
when given column C is > X, otherwise 0. Return a new dataframe with this new column, and keep all the 
previous columns.

In [64]:
c

,air_pressure_9am,air_temp_9am,avg_wind_direction_9am,avg_wind_speed_9am,max_wind_direction_9am,max_wind_speed_9am,rain_accumulation_9am,rain_duration_9am,relative_humidity_9am,relative_humidity_3pm,target
0,918.060000,74.822000,271.100000,2.080354,295.400000,2.863283,0.00,0.0,42.420000,36.160000,1
1,917.347688,71.403843,101.935179,2.443009,140.471548,3.533324,0.00,0.0,24.328697,19.426597,1
2,923.040000,60.638000,51.000000,17.067852,63.700000,22.100967,0.00,20.0,8.900000,14.460000,0
3,920.502751,70.138895,198.832133,4.337363,211.203341,5.190045,0.00,0.0,12.189102,12.742547,1
4,921.160000,44.294000,277.800000,1.856660,136.500000,2.863283,8.90,14730.0,92.410000,76.740000,0
5,915.300000,78.404000,182.800000,9.932014,189.000000,10.983375,0.02,170.0,35.130000,33.930000,1
6,915.598868,70.043304,177.875407,3.745587,186.606696,4.589632,0.00,0.0,10.657422,21.385657,1
7,918.070000,51.710000,242.400000,2.527742,271.600000,3.646212,0.00,0.0,80.470000,74.920000,0
8,920.080000,80.582000,40.700000,4.518619,63.000000,5.883152,0.00,0.0,29.580000,24.030000,1
9,915.010000,47.498000,163.100000,4.943637,195.900000,6.576604,0.00,0.0,88.600000,68.050000,0
10,919.650000,77.036000,70.600000,3.825167,85.500000,4.764682,0.00,0.0,22.070000,32.130000,1
11,915.640000,45.716000,241.600000,5.860783,265.800000,8.030615,0.55,1770.0,90.560000,79.090000,0
12,917.390000,49.784000,204.100000,1.275056,211.800000,2.013246,0.00,0.0,73.150000,58.430000,0
13,920.820000,62.438000,213.600000,2.617220,165.700000,3.310671,0.00,0.0,43.640000,27.990000,0
14,911.000000,86.432000,202.900000,1.207948,162.900000,1.677705,0.00,0.0,15.190000,24.370000,1
15,922.383131,70.865263,36.174175,1.847278,58.428632,2.529142,0.00,0.0,12.110889,14.801706,1
17,916.915255,77.018961,234.539345,2.274725,229.474199,2.906513,0.00,0.0,21.031462,20.755683,1
18,918.800000,67.082000,176.100000,4.876529,183.400000,5.569981,0.00,0.0,18.900000,45.870000,1
19,922.040000,68.576000,58.300000,9.551734,81.900000,12.571603,0.00,0.0,7.540000,7.740000,1
20,919.992262,62.964383,54.799094,12.680436,74.254223,15.452306,0.00,0.0,18.809518,14.649909,0
21,917.230000,67.676000,177.800000,2.460634,93.200000,3.288302,0.00,0.0,40.640000,41.340000,1
22,921.125626,68.818772,71.799092,2.576538,95.472334,3.487444,0.00,0.0,11.742201,17.281161,1
23,920.350000,47.570000,192.100000,6.263432,205.700000,7.605596,0.00,0.0,54.550000,66.000000,0
24,921.788229,71.659572,217.405520,1.946447,253.758003,2.719712,0.00,0.0,11.194250,16.331716,1
25,918.030000,50.666000,128.900000,2.527742,117.400000,4.004123,0.00,0.0,76.880000,47.030000,0
26,914.490000,49.892000,163.000000,4.854160,189.600000,6.733189,0.00,0.0,92.100000,90.990000,0
27,914.900000,78.620000,203.300000,1.811921,240.000000,2.751436,0.00,220.0,47.890000,43.900000,1
28,915.840000,40.118000,171.900000,10.535987,188.000000,12.929513,0.00,0.0,86.430000,84.390000,0
29,916.310000,45.428000,183.100000,8.343786,194.600000,10.088599,0.00,0.0,86.150000,90.580000,0
30,919.350000,91.112000,96.400000,2.527742,96.300000,3.377779,0.00,0.0,25.620000,35.690000,1
...,...,...,...,...,...,...,...,...,...,...,...
1064,913.850000,79.736000,191.700000,3.109347,207.800000,3.981753,0.00,0.0,21.480000,33.190000,1
1065,915.600000,69.584000,185.500000,4.630466,198.200000,5.480503,0.00,0.0,28.970000,39.370000,1
1067,917.690000,64.994000,178.300000,2.975130,193.900000,3.735690,0.00,0.0,54.880000,52.070000,0
1068,920.330000,68.864000,122.400000,2.035615,182.000000,3.086977,0.00,0.0,52.380000,62.620000,1
1069,918.260000,82.220000,186.600000,1.096101,221.500000,1.722444,0.00,0.0,32.460000,56.930000,1
1070,911.600000,46.346000,110.200000,2.304048,96.100000,3.154085,0.00,0.0,90.510000,62.490000,0
1071,919.200000,70.250000,156.700000,2.013246,172.300000,2.617220,0.00,0.0,42.060000,41.850000,1
1072,923.100000,75.596000,178.300000,1.409272,205.200000,1.856660,0.00,0.0,11.880000,19.810000,1
1073,917.920000,84.650000,30.000000,4.831790,40.100000,5.838413,0.00,0.0,16.220000,27.450000,1
1074,913.870000,66.938000,171.900000,6.509495,182.300000,7.471380,0.00,0.0,57.430000,53.380000,1
1075,922.858110,64.989361,63.483047,10.261187,73.170504,11.949206,0.00,0.0,14.525109,15.511157,0
1076,925.550000,50.918000,32.600000,5.413395,57.500000,8.120092,0.00,10.0,29.090000,23.720000,0
1077,920.130000,73.292000,193.600000,4.115970,211.300000,4.966007,0.00,0.0,33.520000,38.120000,1
1078,924.017856,68.370307,56.304083,15.162800,76.585117,19.803578,0.00,0.0,11.599240,9.373013,1
1079,917.200000,65.264000,137.600000,1.767183,176.700000,2.550112,0.00,0.0,58.370000,65.590000,1
1080,916.260000,79.772000,185.700000,3.511996,201.500000,4.160708,0.00,0.0,27.680000,20.400000,1
1081,920.856913,69.884338,47.335966,12.238670,66.729162,16.067860,0.00,0.0,11.956852,12.696233,1
1082,916.130000,50.108000,211.400000,2.550112,231.800000,3.534365,0.00,0.0,89.800000,53.860000,0
1083,916.320000,48.308000,46.900000,4.854160,61.700000,5.860783,0.00,0.0,91.030000,62.400000,0
1084,917.130000,80.240000,183.300000,1.632966,38.500000,2.259309,0.00,0.0,28.260000,34.690000,1
1085,914.840000,47.354000,190.900000,3.713320,204.400000,4.652835,0.00,0.0,92.300000,88.160000,0
1086,921.260000,52.646000,261.900000,2.035615,260.500000,3.042238,0.00,0.0,91.110000,81.890000,0
1087,914.000000,66.650000,173.800000,8.366156,181.000000,9.439887,0.00,0.0,30.920000,47.340000,1
1088,912.900000,71.870000,129.200000,1.431642,160.000000,2.057985,0.00,0.0,51.840000,55.490000,1
1089,915.000000,55.040000,191.800000,5.368656,220.900000,7.068730,0.00,0.0,73.550000,69.670000,0
1090,918.900000,63.104000,192.900000,3.869906,207.300000,5.212070,0.00,0.0,26.020000,38.180000,0
1091,918.710000,49.568000,241.600000,1.811921,227.400000,2.371156,0.00,0.0,90.350000,73.340000,0
1092,916.600000,71.096000,189.300000,3.064608,200.800000,3.892276,0.00,0.0,45.590000,52.310000,1
1093,912.600000,58.406000,172.700000,3.825167,189.100000,4.764682,0.00,0.0,64.840000,58.280000,0
1094,921.530000,77.702000,97.100000,3.265932,125.900000,4.451511,0.00,0.0,14.560000,15.100000,1

In [71]:
# modify this cell

def classification_task(df, C, X):
    ### BEGIN SOLUTION
    newdf = df
    newdf['target'] = [1 if v > X else 0 for v in df[C]]
    return(newdf)
    ### END SOLUTION

In [72]:
# DO NOT MODIFY

ans = 558

try: 
    c = classification_task(df2, 'air_temp_9am', 65.0)
    assert np.alltrue(c['target'].sum() == ans)
except AssertionError as e: print("Try again, your solution did not produce the expected output above")

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ipykernel/__main__.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [67]:
del c['number']

In [68]:
def get_ready(df):
    from sklearn.model_selection import train_test_split
    # declare features to use
    features = ['air_pressure_9am','avg_wind_direction_9am','avg_wind_speed_9am','max_wind_direction_9am']
    # create copy
    df_copy = df.copy()
    df_copy['target'] = (df_copy['air_temp_9am'] > 65.0)*1
    # separate features from target
    X=df_copy[features]
    y=df_copy['target']
    # perform split and return
    return train_test_split(X, y, test_size=0.33, random_state=983)

In [70]:
X_train, X_test, y_train, y_test = get_ready(pd.read_csv('../weather/daily_weather.csv').dropna())

<p style="font-family: Arial; font-size:2.75vw;color:purple; font-style:bold"><br>

Exercise 4: Create a Classifier<br><br></p>

In the cell below, modify the function to take X_train, y_train only and RETURN a classifier
for predicting the y_train based on columns in X_train. You can pick any classifier model.

The function should RETURN a trained model. We will test your classifier on X_test and y_test

In [83]:
# modify this cell

def train_classifier(X_train, y_train):
    ### BEGIN SOLUTION
    t_classifier = DecisionTreeClassifier(max_leaf_nodes=50, random_state=0)
    t_classifier.fit(X_train, y_train)
    return(t_classifier)
    ### END SOLUTION

In [84]:
# DO NOT MODIFY

min_score = 0.63

try: 
    v = train_classifier(X_train, y_train)
    y_pred = v.predict(X_test)
    assert np.alltrue(accuracy_score(y_test, y_pred) > min_score)
except AssertionError as e: print("Keep trying - can you get an accuracy_score > %f" % min_score)